name: ${plugin.name}
version: ${project.version}
main: ${plugin.main.classpath}
api-version: 1.13
author: Fr33styler
depend:
  - Vault
load: STARTUP
commands:
  money:
    description: Show money.
    aliases: [bal]
  pay:
    description: Pay money.
  balTop:
    description: Show top users.
  eco:
    description: Admin money management.